/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.eventconnect.connectevent.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.eventconnect.connectevent.models.query.*;

public interface ConnecteventQueryExecutorService {

    Page<GetEventDetailsByLoginIdResponse> executeGetEventDetailsByLoginId(String id, Pageable pageable);

    void exportGetEventDetailsByLoginId(String id, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EventSpeakerDetailsResponse> executeEventSpeakerDetails(String eventId, Pageable pageable);

    void exportEventSpeakerDetails(String eventId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EventSpeakerDetails1Response> executeEventSpeakerDetails1(String eventId, String speakerId, Pageable pageable);

    void exportEventSpeakerDetails1(String eventId, String speakerId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EventSpeakerDetailsEventIdResponse> executeEventSpeakerDetailsEventID(String eventId, Pageable pageable);

    void exportEventSpeakerDetailsEventID(String eventId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}