/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.eventconnect.connectevent.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.eventconnect.connectevent.models.query.*;

@Service
public class ConnecteventQueryExecutorServiceImpl implements ConnecteventQueryExecutorService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ConnecteventQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("connecteventWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "connecteventTransactionManager", readOnly = true)
    @Override
    public Page<GetEventDetailsByLoginIdResponse> executeGetEventDetailsByLoginId(String id, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("id", id);

        return queryExecutor.executeNamedQuery("getEventDetailsByLoginId", params, GetEventDetailsByLoginIdResponse.class, pageable);
    }

    @Transactional(value = "connecteventTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportGetEventDetailsByLoginId(String id, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("id", id);

        QueryProcedureInput<GetEventDetailsByLoginIdResponse> queryInput = new QueryProcedureInput<>("getEventDetailsByLoginId", params, GetEventDetailsByLoginIdResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "connecteventTransactionManager", readOnly = true)
    @Override
    public Page<EventSpeakerDetailsResponse> executeEventSpeakerDetails(String eventId, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("EventID", eventId);

        return queryExecutor.executeNamedQuery("EventSpeakerDetails", params, EventSpeakerDetailsResponse.class, pageable);
    }

    @Transactional(value = "connecteventTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportEventSpeakerDetails(String eventId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("EventID", eventId);

        QueryProcedureInput<EventSpeakerDetailsResponse> queryInput = new QueryProcedureInput<>("EventSpeakerDetails", params, EventSpeakerDetailsResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "connecteventTransactionManager", readOnly = true)
    @Override
    public Page<EventSpeakerDetails1Response> executeEventSpeakerDetails1(String eventId, String speakerId, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("EventID", eventId);
        params.put("SpeakerID", speakerId);

        return queryExecutor.executeNamedQuery("EventSpeakerDetails1", params, EventSpeakerDetails1Response.class, pageable);
    }

    @Transactional(value = "connecteventTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportEventSpeakerDetails1(String eventId, String speakerId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(2);

        params.put("EventID", eventId);
        params.put("SpeakerID", speakerId);

        QueryProcedureInput<EventSpeakerDetails1Response> queryInput = new QueryProcedureInput<>("EventSpeakerDetails1", params, EventSpeakerDetails1Response.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

    @Transactional(value = "connecteventTransactionManager", readOnly = true)
    @Override
    public Page<EventSpeakerDetailsEventIdResponse> executeEventSpeakerDetailsEventID(String eventId, Pageable pageable) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("EventID", eventId);

        return queryExecutor.executeNamedQuery("EventSpeakerDetailsEventID", params, EventSpeakerDetailsEventIdResponse.class, pageable);
    }

    @Transactional(value = "connecteventTransactionManager", timeout = 300, readOnly = true)
    @Override
    public void exportEventSpeakerDetailsEventID(String eventId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream) {
        Map<String, Object> params = new HashMap<>(1);

        params.put("EventID", eventId);

        QueryProcedureInput<EventSpeakerDetailsEventIdResponse> queryInput = new QueryProcedureInput<>("EventSpeakerDetailsEventID", params, EventSpeakerDetailsEventIdResponse.class);

        queryExecutor.exportNamedQueryData(queryInput, exportOptions, pageable, outputStream);
    }

}