/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.eventconnect.connectevent.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class EventSpeakerDetailsResponse implements Serializable {


    @ColumnAlias("Id")
    private Long id;

    @ColumnAlias("Name")
    private String name;

    @ColumnAlias("Bio")
    private String bio;

    @ColumnAlias("PhotoUrl")
    private String photoUrl;

    @ColumnAlias("LinkedInUrl")
    private String linkedInUrl;

    @ColumnAlias("TwitterUrl")
    private String twitterUrl;

    @ColumnAlias("PortfolioUrl")
    private String portfolioUrl;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBio() {
        return this.bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public String getPhotoUrl() {
        return this.photoUrl;
    }

    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    public String getLinkedInUrl() {
        return this.linkedInUrl;
    }

    public void setLinkedInUrl(String linkedInUrl) {
        this.linkedInUrl = linkedInUrl;
    }

    public String getTwitterUrl() {
        return this.twitterUrl;
    }

    public void setTwitterUrl(String twitterUrl) {
        this.twitterUrl = twitterUrl;
    }

    public String getPortfolioUrl() {
        return this.portfolioUrl;
    }

    public void setPortfolioUrl(String portfolioUrl) {
        this.portfolioUrl = portfolioUrl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EventSpeakerDetailsResponse)) return false;
        final EventSpeakerDetailsResponse eventSpeakerDetailsResponse = (EventSpeakerDetailsResponse) o;
        return Objects.equals(getId(), eventSpeakerDetailsResponse.getId()) &&
                Objects.equals(getName(), eventSpeakerDetailsResponse.getName()) &&
                Objects.equals(getBio(), eventSpeakerDetailsResponse.getBio()) &&
                Objects.equals(getPhotoUrl(), eventSpeakerDetailsResponse.getPhotoUrl()) &&
                Objects.equals(getLinkedInUrl(), eventSpeakerDetailsResponse.getLinkedInUrl()) &&
                Objects.equals(getTwitterUrl(), eventSpeakerDetailsResponse.getTwitterUrl()) &&
                Objects.equals(getPortfolioUrl(), eventSpeakerDetailsResponse.getPortfolioUrl());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getName(),
                getBio(),
                getPhotoUrl(),
                getLinkedInUrl(),
                getTwitterUrl(),
                getPortfolioUrl());
    }
}