/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.eventconnect.connectevent.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetEventDetailsByLoginIdResponse implements Serializable {


    @ColumnAlias("Id")
    private Long id;

    @ColumnAlias("Title")
    private String title;

    @ColumnAlias("OrganizerName")
    private String organizerName;

    @ColumnAlias("OrganizerEmail")
    private String organizerEmail;

    @ColumnAlias("OrganizerPhNo")
    private String organizerPhNo;

    @ColumnAlias("About")
    private String about;

    @ColumnAlias("Location")
    private String location;

    @ColumnAlias("Fee")
    private String fee;

    @ColumnAlias("StartDate")
    private Date startDate;

    @ColumnAlias("EndDate")
    private Date endDate;

    @ColumnAlias("StartTime")
    private Time startTime;

    @ColumnAlias("EndTime")
    private Time endTime;

    @ColumnAlias("Poster")
    private String poster;

    @ColumnAlias("IsOnline")
    private Boolean isOnline;

    @ColumnAlias("MeetingLink")
    private String meetingLink;

    @ColumnAlias("Status")
    private String status;

    @ColumnAlias("User_Id")
    private Long userId;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getOrganizerName() {
        return this.organizerName;
    }

    public void setOrganizerName(String organizerName) {
        this.organizerName = organizerName;
    }

    public String getOrganizerEmail() {
        return this.organizerEmail;
    }

    public void setOrganizerEmail(String organizerEmail) {
        this.organizerEmail = organizerEmail;
    }

    public String getOrganizerPhNo() {
        return this.organizerPhNo;
    }

    public void setOrganizerPhNo(String organizerPhNo) {
        this.organizerPhNo = organizerPhNo;
    }

    public String getAbout() {
        return this.about;
    }

    public void setAbout(String about) {
        this.about = about;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getFee() {
        return this.fee;
    }

    public void setFee(String fee) {
        this.fee = fee;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Time getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Time startTime) {
        this.startTime = startTime;
    }

    public Time getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Time endTime) {
        this.endTime = endTime;
    }

    public String getPoster() {
        return this.poster;
    }

    public void setPoster(String poster) {
        this.poster = poster;
    }

    public Boolean getIsOnline() {
        return this.isOnline;
    }

    public void setIsOnline(Boolean isOnline) {
        this.isOnline = isOnline;
    }

    public String getMeetingLink() {
        return this.meetingLink;
    }

    public void setMeetingLink(String meetingLink) {
        this.meetingLink = meetingLink;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetEventDetailsByLoginIdResponse)) return false;
        final GetEventDetailsByLoginIdResponse getEventDetailsByLoginIdResponse = (GetEventDetailsByLoginIdResponse) o;
        return Objects.equals(getId(), getEventDetailsByLoginIdResponse.getId()) &&
                Objects.equals(getTitle(), getEventDetailsByLoginIdResponse.getTitle()) &&
                Objects.equals(getOrganizerName(), getEventDetailsByLoginIdResponse.getOrganizerName()) &&
                Objects.equals(getOrganizerEmail(), getEventDetailsByLoginIdResponse.getOrganizerEmail()) &&
                Objects.equals(getOrganizerPhNo(), getEventDetailsByLoginIdResponse.getOrganizerPhNo()) &&
                Objects.equals(getAbout(), getEventDetailsByLoginIdResponse.getAbout()) &&
                Objects.equals(getLocation(), getEventDetailsByLoginIdResponse.getLocation()) &&
                Objects.equals(getFee(), getEventDetailsByLoginIdResponse.getFee()) &&
                Objects.equals(getStartDate(), getEventDetailsByLoginIdResponse.getStartDate()) &&
                Objects.equals(getEndDate(), getEventDetailsByLoginIdResponse.getEndDate()) &&
                Objects.equals(getStartTime(), getEventDetailsByLoginIdResponse.getStartTime()) &&
                Objects.equals(getEndTime(), getEventDetailsByLoginIdResponse.getEndTime()) &&
                Objects.equals(getPoster(), getEventDetailsByLoginIdResponse.getPoster()) &&
                Objects.equals(getIsOnline(), getEventDetailsByLoginIdResponse.getIsOnline()) &&
                Objects.equals(getMeetingLink(), getEventDetailsByLoginIdResponse.getMeetingLink()) &&
                Objects.equals(getStatus(), getEventDetailsByLoginIdResponse.getStatus()) &&
                Objects.equals(getUserId(), getEventDetailsByLoginIdResponse.getUserId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getTitle(),
                getOrganizerName(),
                getOrganizerEmail(),
                getOrganizerPhNo(),
                getAbout(),
                getLocation(),
                getFee(),
                getStartDate(),
                getEndDate(),
                getStartTime(),
                getEndTime(),
                getPoster(),
                getIsOnline(),
                getMeetingLink(),
                getStatus(),
                getUserId());
    }
}